apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-rhtap-he
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/test-rhtap-he/overlays/development
    repoURL: https://github.com/prietyc123-qe-org/test-rhtap-he-gitops
    targetRevision: main
  destination:
    namespace: pkumari
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
