apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: test-rhtap-he-gitops
  description: This is GitOps manifest for test-rhtap-he   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:test-rhtap-he
