apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: test-rhtap-he
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-rhtap-he 
  name: test-rhtap-he
  namespace: pkumari
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: test-rhtap-he
    weight: 100 
