apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-rhtap-he
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-rhtap-he 
  name: test-rhtap-he
  namespace: pkumari
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: test-rhtap-he 
